-------CURATED LAYER (GOLD)

USE DATABASE ABCD_DB;
USE SCHEMA CURATED_ABC_SCHEMA;
CREATE OR REPLACE TABLE FACT_INSURANCE AS
SELECT
   
    p.POLICY_ID,
    p.CUSTOMER_ID,
    p.AGENT_ID,
    p.UNDERWRITER_ID,

   
    c.NAME,
    c.AGE,
    c.GENDER,
    c.STATE,
    c.RISK_SCORE AS CUSTOMER_RISK_SCORE,

    p.POLICY_TYPE,
    p.PRODUCT_NAME,
    p.POLICY_STATUS,
    p.PREMIUM_AMOUNT,
    p.SUM_ASSURED,
    p.START_DATE,
    p.END_DATE,

    
    cl.CLAIM_ID,
    cl.CLAIM_DATE,
    cl.REPORTED_DATE,
    cl.CLAIM_AMOUNT,
    cl.APPROVED_AMOUNT,
    cl.CLAIM_STATUS,
    cl.IS_FLAGGED,

   
    r.RISK_CATEGORY,
    r.RISK_FACTOR,
    r.RISK_SCORE AS POLICY_RISK_SCORE,

    
    a.AGENT_NAME,
    a.REGION,

    
    CURRENT_TIMESTAMP() AS CREATED_AT

FROM VALIDATED_ABC_SCHEMA.VALIDATED_POLICY p

LEFT JOIN VALIDATED_ABC_SCHEMA.VALIDATED_CUSTOMER c
    ON TRIM(UPPER(p.CUSTOMER_ID)) = TRIM(UPPER(c.CUSTOMER_ID))

LEFT JOIN VALIDATED_ABC_SCHEMA.VALIDATED_CLAIMS cl
    ON TRIM(UPPER(p.POLICY_ID)) = TRIM(UPPER(cl.POLICY_ID))

LEFT JOIN VALIDATED_ABC_SCHEMA.VALIDATED_RISK r
    ON TRIM(UPPER(p.POLICY_ID)) = TRIM(UPPER(r.POLICY_ID))

LEFT JOIN VALIDATED_ABC_SCHEMA.VALIDATED_AGENTS a
    ON TRIM(UPPER(p.AGENT_ID)) = TRIM(UPPER(a.AGENT_ID));
select * from fact_insurance;
